nelmio_api_doc:
    documentation:
        info:
            title: 'Mi API'
            description: 'Descripción de mi API'
            version: '1.0.0'
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    models:
        names:
            Transaction:
                alias: 'Transaction'
                type: 'App\Entity\Transaction'