#index:
#    path: /
#    controller: App\Controller\DefaultController::index

transaction_index:
    path: /transactions
    controller: App\Controller\TransactionController::index

transaction_new:
    path: /transactions/new
    controller: App\Controller\TransactionController::new